/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Visualizador;
/**
 *
 * @author Miguel Torrres
 */
public class SelectorElementoConsulta extends javax.swing.JFrame {

    /**
     * Creates new form SelectorElementoConsulta
     */
    public String elementoDeConsulta = "";
    
    public SelectorElementoConsulta() {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxElementoConsulta = new javax.swing.JComboBox<>();
        botonSeleccionarElementoConsulta = new javax.swing.JButton();
        botonCancelarElementoConsulta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menú de Selección");
        setLocation(new java.awt.Point(600, 400));

        comboBoxElementoConsulta.setBackground(new java.awt.Color(204, 204, 204));
        comboBoxElementoConsulta.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        comboBoxElementoConsulta.setForeground(new java.awt.Color(0, 153, 153));
        comboBoxElementoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afiliaciones", "Citas por Especialidad", "Citas por Exámenes", "Citas para Otros Servicios", "Quejas y Comunicaciones Directas con Clientes" }));
        comboBoxElementoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxElementoConsultaActionPerformed(evt);
            }
        });

        botonSeleccionarElementoConsulta.setBackground(new java.awt.Color(0, 255, 0));
        botonSeleccionarElementoConsulta.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        botonSeleccionarElementoConsulta.setText("Seleccionar");
        botonSeleccionarElementoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeleccionarElementoConsultaActionPerformed(evt);
            }
        });

        botonCancelarElementoConsulta.setBackground(new java.awt.Color(207, 6, 59));
        botonCancelarElementoConsulta.setFont(new java.awt.Font("Century", 1, 14)); // NOI18N
        botonCancelarElementoConsulta.setForeground(new java.awt.Color(255, 255, 255));
        botonCancelarElementoConsulta.setText("Cancelar");
        botonCancelarElementoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarElementoConsultaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel1.setText("Seleccione del menú a continuación el que será el elemento de su consulta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(botonSeleccionarElementoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonCancelarElementoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxElementoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboBoxElementoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonSeleccionarElementoConsulta)
                    .addComponent(botonCancelarElementoConsulta))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxElementoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxElementoConsultaActionPerformed
        
        
    }//GEN-LAST:event_comboBoxElementoConsultaActionPerformed

    private void botonSeleccionarElementoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarElementoConsultaActionPerformed
        elementoDeConsulta = comboBoxElementoConsulta.getSelectedItem()+"";
        System.out.println("Elemento seleccionado en el menú: " + comboBoxElementoConsulta.getSelectedItem()+"");
        this.dispose();
    }//GEN-LAST:event_botonSeleccionarElementoConsultaActionPerformed

    private void botonCancelarElementoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarElementoConsultaActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarElementoConsultaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarElementoConsulta;
    private javax.swing.JButton botonSeleccionarElementoConsulta;
    private javax.swing.JComboBox<String> comboBoxElementoConsulta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
